In [1]:
import numpy as np
# creating 1d array
n1=np.array([5,6,7,8])
print(n1)

[5 6 7 8]


In [2]:
# creating 2d array
n2=np.array([[3,4,5,6],[1,2,10,9]])
print(n2)

[[ 3  4  5  6]
 [ 1  2 10  9]]


In [3]:
#zero filled 2d array
n3=np.zeros([3,5],dtype="int32")
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [4]:
#array filled with ones
n4=np.ones([2,3,3],dtype="int32")
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [5]:
# empty array - contains random junk values
n5=np.empty([1,3])
print(n5)

[[ 1.67889981e+251  1.17163250e-311 -0.00000000e+000]]


In [6]:
# create array with range values
n6=np.arange(10)
print(n6)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
n7= np.arange(-5,30,5) # start stop step
print(n7)

[-5  0  5 10 15 20 25]


In [8]:
# linearly spaced entries
n8=np.linspace(0,20,num=8)
print(n8)

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


In [9]:
n9= np.full([2,5],99)
print(n9)

[[99 99 99 99 99]
 [99 99 99 99 99]]


In [10]:
n5.fill(9)
print(n5)

[[9. 9. 9.]]
