In [1]:
import numpy as np
# creating 1d array
n1=np.array([5,6,7,8])
print(n1)

[5 6 7 8]


In [2]:
# creating 2d array
n2=np.array([[3,4,5,6],[1,2,10,9]])
print(n2)

[[ 3  4  5  6]
 [ 1  2 10  9]]


In [3]:
#zero filled 2d array
n3=np.zeros([3,5],dtype="int32")
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [4]:
#array filled with ones
n4=np.ones([2,3,3],dtype="int32")
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [5]:
# empty array - contains random junk values
n5=np.empty([1,3])
print(n5)

[[1.05174001e-311 0.00000000e+000 1.05038792e-311]]


In [6]:
# create array with range values
n6=np.arange(10)
print(n6)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
n7= np.arange(-5,30,5) # start stop step
print(n7)

[-5  0  5 10 15 20 25]


In [8]:
# linearly spaced entries
n8=np.linspace(0,20,num=8)
print(n8)

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


In [9]:
n9= np.full([2,5],99)
print(n9)

[[99 99 99 99 99]
 [99 99 99 99 99]]


In [10]:
n5.fill(9)
print(n5)

[[9. 9. 9.]]


# Accessing

In [11]:
print(n2[1,0])

1


In [12]:
print(n1[-1])

8


In [13]:
print(n2[1,:])

[ 1  2 10  9]


In [14]:
n4[1,1,2] = 10
print(n4)

[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1  1 10]
  [ 1  1  1]]]


# Size And Shape

In [15]:
print(n4.ndim) # idim gives no.of dimensions or axes

3


In [16]:
print(n4.shape)

(2, 3, 3)


In [17]:
print(n4.size)

18


In [18]:
print(n4.dtype)

int32


In [19]:
print(n4.itemsize)

4


In [20]:
print(n4.nbytes)

72


# Sorting

In [21]:
n10= np.array([3,4,1,9,5,10,7,8])
np.sort(n10)

array([ 1,  3,  4,  5,  7,  8,  9, 10])

In [22]:
n11= np.array([[3,4,1,9],[5,10,7,8]])
np.sort(n11)

array([[ 1,  3,  4,  9],
       [ 5,  7,  8, 10]])

In [23]:
np.sort(n11,axis=0)

array([[ 3,  4,  1,  8],
       [ 5, 10,  7,  9]])

In [24]:
np.sort(n11,axis=1)

array([[ 1,  3,  4,  9],
       [ 5,  7,  8, 10]])

# Reshaping and Array Convertions

In [25]:
n12=n10.reshape(4,2)
print(n12)

[[ 3  4]
 [ 1  9]
 [ 5 10]
 [ 7  8]]


In [26]:
# joining 2 arrays using concatenate
n13=np.arange(4)
print(n13)
n14=np.arange(5,9)
print(n14)
n15 = np.concatenate((n13,n14))
print(n15)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


In [27]:
# converting 1d array to 2d array
n16= np.arange(8)
print(n16)
n17=n16[np.newaxis,:]
print(n17)
print(n17.shape)
n18=n16[:,np.newaxis]
print(n18)
print(n18.shape)

[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]]
(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [28]:
n19 = np.expand_dims(n16,axis = 1)
print(n19)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [29]:
n20 = np.expand_dims(n16,axis = 0)
print(n20)

[[0 1 2 3 4 5 6 7]]


# Indexing And Slicing

In [30]:
n21= np.arange(10)
print(n21)
print(n21[n21 < 5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [31]:
print(n21[(n21>3) & (n21<8)])

[4 5 6 7]


In [32]:
five_up = n21>5
print(five_up)
print(n21[five_up])

[False False False False False False  True  True  True  True]
[6 7 8 9]


In [33]:
print(np.nonzero(n21>5))

(array([6, 7, 8, 9], dtype=int64),)


In [34]:
print(n21[3:7])

[3 4 5 6]


# Stack Split

In [35]:
n22= np.array([[1,2],[3,4]])
n23=np.array([[5,6],[7,8]])
np.hstack((n22,n23))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [36]:
np.vstack((n22,n23))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
n24 = np.arange(20)
print(n24)
np.hsplit(n24,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

# Copy







In [38]:
n25 = n24[0:5] # shallow copy
n24[0] = 100
print(n24)
print(n25)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100   1   2   3   4]


In [39]:
3 # deep copy
n26 = n24.copy()
n24[0]=200
print(n24)
print(n26)

[200   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


# Math

In [40]:
print(n22)
print(n23)
print(n22+n23)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [41]:
print(np.cos(n26))

[ 0.86231887  0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


In [42]:
print(n26)
print(n26.sum())
print(n26.max())
print(n26.min())
print(n26*5)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
290
100
1
[500   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95]
